[CIAS30-3854] send PDP invitation to the session
Michigan-State-University/cias-api pull request #223
Opened 2023-12-15 09:09 UTC by WiktoriaRozanska

## Related tasks
- [CIAS-3854](https://htdevelopers.atlassian.net/browse/CIAS30-3854)

## What's new?
-

2023-12-19 09:27 UTC, bartosz-kepka-htd commented on app/services/v1/user_session_schedule_service.rb
> +    schedule_until(DateTime.now + next_session.schedule_payload.seconds, next_session)
It looks like this change should be reverted 🤔

2024-01-22 09:54 UTC, mimbor requested changes

2024-01-22 18:09 UTC, WiktoriaRozanska commented on app/jobs/session_schedule_job.rb
> +      return unless settings.email_notification
I think I don't understand you here, could you elaborate on this?

2024-01-26 07:48 UTC, mimbor commented on app/jobs/session_schedule_job.rb
> +      return unless settings.email_notification
I mean something like:
```suggestion
      settings = user.predefined_user_parameter
      return unless settings.email_notification
      session&.send_sms_to_session(user, health_clinic)
```

2024-01-26 08:03 UTC, mimbor approved these changes

2024-01-26 08:31 UTC, merged